//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoirParts
    {
        public ChoirParts()
        {
            this.CodeAlgorithm = new HashSet<CodeAlgorithm>();
            this.Members = new HashSet<Members>();
        }
    
        public int sn { get; set; }
        public string Part { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<CodeAlgorithm> CodeAlgorithm { get; set; }
        public virtual ICollection<Members> Members { get; set; }
    }
}
