//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeAlgorithm
    {
        public int sn { get; set; }
        public string Year { get; set; }
        public int Part_id { get; set; }
        public int LastNumber { get; set; }
    
        public virtual ChoirParts ChoirParts { get; set; }
    }
}
