//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class defaultcon : DbContext
    {
        public defaultcon()
            : base("name=defaultcon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academy> Academy { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<ChoirParts> ChoirParts { get; set; }
        public virtual DbSet<ChoirSplits> ChoirSplits { get; set; }
        public virtual DbSet<CodeAlgorithm> CodeAlgorithm { get; set; }
        public virtual DbSet<Dues> Dues { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FriendshipGroups> FriendshipGroups { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MonthlyDues> MonthlyDues { get; set; }
        public virtual DbSet<NextOfKins> NextOfKins { get; set; }
        public virtual DbSet<Occupations> Occupations { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<States> States { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    }
}
