//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int MemberId { get; set; }
        public string Code { get; set; }
        public string LastName { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string MaritalStatus { get; set; }
        public string HomeAddress { get; set; }
        public string OfficeAddress { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> Wedding { get; set; }
        public int OccupationId { get; set; }
        public string Nickname { get; set; }
        public int ChoirSplit_Id { get; set; }
        public int AvailabilityId { get; set; }
        public string Remarks { get; set; }
        public int StateOfOriginId { get; set; }
        public string LGA { get; set; }
        public string Photo { get; set; }
        public string RobeNo { get; set; }
        public int PartId { get; set; }
        public System.DateTime JoinedOn { get; set; }
        public Nullable<int> PostId { get; set; }
        public string HomeTown { get; set; }
        public int Friendship_Id { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> Attendance_id { get; set; }
        public Nullable<int> Academy_Id { get; set; }
        public Nullable<int> Application_id { get; set; }
    
        public virtual Academy Academy { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ChoirParts ChoirParts { get; set; }
        public virtual ChoirSplits ChoirSplits { get; set; }
        public virtual FriendshipGroups FriendshipGroups { get; set; }
        public virtual Occupations Occupations { get; set; }
        public virtual Posts Posts { get; set; }
        public virtual States States { get; set; }
        public virtual NextOfKins NextOfKins { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
